### ISSUE TITLE
getting base64 data

### ISSUE THREAD

**Issue by kimsean** [jamesssooi/Croppr.js#22]
is it possible to get the base64 data of the cropped image? if so how ? thank you.

**Comment by jamesssooi** [comment]
Hi @kimsean, Croppr's main role is to just provide an interface to get the crop values so that other services (such as your backend) can do the actual cropping.

Cropping can be done entirely on the frontend of course, but you'll have to implement it yourself, and it is not a part of Croppr. Here's a link to get you started: 
* [https://yellowpencil.com/blog/cropping-images-with-javascript/](https://yellowpencil.com/blog/cropping-images-with-javascript/)

Duplicate of #3
