### ISSUE TITLE
How to crop the image and get the dataUrl?

### ISSUE THREAD

**Issue by sahandnayebaziz** [jamesssooi/Croppr.js#3]
I understand how to set Croppr up, but how do I actually get the cropped image after the user is done cropping the image?

**Comment by jamesssooi** [comment]
Croppr does not actually crop the image for you. It's function is to simply retrieve the cropping coordinates so that other services (such as your backend) can do the actual cropping. It was made on the understanding that it's safer to perform server-side image manipulation rather than trusting the user's input entirely.

However, if you do insist on performing client-side cropping (or a mix of both), you are free to use your own implementation for the actual image cropping part. You can refer to these links for further information:

- https://yellowpencil.com/blog/cropping-images-with-javascript/ (Refer to step 4)
- http://stackoverflow.com/questions/17402948/crop-and-upload-image-on-client-side-without-server-side-code-involve

**Comment by sahandnayebaziz** [comment]
Ah, I see. Wonderful. Thank you @jamesssooi :)
